name: "WD-Utils"
author: "xxAROX"
version: "1.0.0"
main: "xxAROX.WDUtils.WDUtilsPlugin"

permissions:
  "waterdog.command.reload":
    description: "Allows to reload the plugins"
  "waterdog.command.plugins":
    description: "Allows to see plugins"
