name: "WD-Utils"
author: "xxAROX"
version: "1.0.5"
main: "xxAROX.WDUtils.WDUtilsPlugin"
softdepend:
  - "WD-Forms"

permissions:
  "waterdog.command.reload":
    description: "Allows to reload the plugins"
  "waterdog.command.plugins":
    description: "Allows to see plugins"
  "waterdog.command.lang.reload":
    description: "Allows to reload any language-manager"
